language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*

addons:
  code_climate:
      repo_token: f0a01fd708e8f258d3532dd82d1b55c3873953ad56fa2796d178483b9c9d6228

before_script:

    # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
    - "mkdir -p ~/.composer"
    - cp .travis.composer.config.json ~/.composer/config.json
    - composer self-update
    - composer require symfony/asset:${SYMFONY_VERSION} --no-update
    - composer require symfony/intl:${SYMFONY_VERSION} --no-update
    - composer require symfony/event-dispatcher:${SYMFONY_VERSION} --no-update
    - composer require symfony/options-resolver:${SYMFONY_VERSION} --no-update
    - composer require symfony/form:${SYMFONY_VERSION} --no-update
    - composer require symfony/twig-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/twig-bridge:${SYMFONY_VERSION} --no-update
    - composer require symfony/templating:${SYMFONY_VERSION} --no-update
    - composer require symfony/doctrine-bridge:${SYMFONY_VERSION} --no-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}
    - composer install --dev

notifications:
  email: vitiko@mail.ru
